### ISSUE TITLE
Unusable on Steam Deck (Cannot resize to fit screen)

### ISSUE THREAD

**Issue by z3rglingboss** [NiceneNerd/ukmm#122] opened 2023-05-12 20:09 UTC
Currently unusable on Steam Deck unless you have a 2nd, large monitor.

UKMM's minimum size is about twice the size of the Steam Deck's 1280x800

**Comment by davdandlv** [comment] 2023-05-12 20:33
In the meantime, fix is in the docs:
https://nicenenerd.github.io/ukmm/troubleshooting.html

```
This happens on some systems, particularly Steam Deck, for unknown reasons, but can be fixed by setting the environment variable WINIT_X11_SCALE_FACTOR=1.0.
```

**Comment by NiceneNerd** [comment] 2023-05-12 23:24
Duplicate of several others.

**Closed by NiceneNerd** 2023-05-12 23:24 UTC
