### ISSUE TITLE
Failed to convert BNP to UKMM mod

### ISSUE THREAD

**Issue by thisisonlyme** [NiceneNerd/ukmm#113] opened 2023-05-03 23:31 UTC
While trying to install mods to a profile, almost all mods in the bnp format fail with this error message:

"Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack BNP at `crates\uk-manager\src\bnp.rs@399:42`
    1: Failed to process gamedata log at `crates\uk-manager\src\bnp.rs@290:14`
    2: BYML file missing key: FlagData missing DataName"

Any idea what's causing this?

**Comment by NiceneNerd** [comment] 2023-05-04 04:23
Do you have any examples? This can only happen to mods which modify gamedata, which many do not. It _looks_ like the type of error that should be the mod's fault, but without inspecting one of the mods it would be hard to be sure.

**Comment by yehorb** [comment] 2023-05-04 07:23
I had a similar issue, and it got resolved by setting the correct console language in the settings. I had a European ROM, but my console language was USen. And most of the mods were failing to convert. After setting the correct EUen language in the settings, mods were successfully installed.

**Comment by NiceneNerd** [comment] 2023-05-04 13:06
That's not a similar issue

**Comment by thisisonlyme** [comment] 2023-05-04 23:53
this failed with the island expansion dlc mod, and a shader mod, and some other mods that I can't think of off the top of my head.

**Comment by NiceneNerd** [comment] 2023-05-05 01:48
With the exact same error each time?

**Comment by Highlander1536** [comment] 2023-05-07 05:39
tried SecondWindv1.9.10a_switch.bnp and it noped out

**Comment by NiceneNerd** [comment] 2023-05-07 12:39
As has been noted a number of times, none of the current Second Wind builds work on UKMM due chiefly to problems internal to Second Wind which must be fixed on their part. They are working on it and it will be resolved in the next release.

**Comment by thisisonlyme** [comment] 2023-05-07 19:28
Yes, this happened every time. I don't know why you don't get it with the island expansion; it doesn't work for me.

**Comment by NiceneNerd** [comment] 2023-05-08 02:52
And it's always that exact same error message no matter which mod it is? Even simple retextures?

**Comment by thisisonlyme** [comment] 2023-05-08 21:38
Yup. I thought I'd fixed it, just now, because I had apperantly moved some files, but turns out that was after I got this error. Weirder, is that I just switched to v082, and I'm getting a different error now.

**Comment by NiceneNerd** [comment] 2023-05-09 13:05
The problem is that error can _only_ occur on mods that edit gamedata flags, so it's impossible to get on simple retextures. Try installing a simple skin and pasting the error details.

**Comment by thisisonlyme** [comment] 2023-05-09 20:58
Clarification: _some_ skins don't work. The world editing mods do not.

As for what you said, you want me to install a simple retexture, and if it gives an error, post it here? Do you have any recommended mods for this? I don't know what constitutes simple in this context.

**Comment by NiceneNerd** [comment] 2023-05-09 21:13
"Simple" in this case means it does absolutely nothing whatsoever except retexture an existing item.

**Comment by thisisonlyme** [comment] 2023-05-09 22:47
Mods like that seem to work fine.

**Comment by NiceneNerd** [comment] 2023-05-09 23:07
That is clarifying. But I still can't really replicate it. Are you sure your dump is good?

**Comment by thisisonlyme** [comment] 2023-05-09 23:22
I don't know how to verify, but I dumped it straight from my Wii U via dumpling, so I _think_ it is.

**Closed** 2023-05-23 16:48 UTC
