### ISSUE TITLE
Doesn't Like Second Wind

### ISSUE THREAD

**Issue by NateHevens** [NiceneNerd/ukmm#19] opened 2023-01-30 18:04 UTC
I hope it's okay that I'm putting this here. Feel free to yell at me if I'm wrong to.

UKMM doesn't appear to like Second Wind. I get various different processing errors, although they all seem to be related to missing info. Here's the most recent:

> Failed to process SARC file Actor/Pack/ElementalRodAttack.bactorpack
> 
> Caused by:
>     0: Failed to parse resource Actor/AIProgram/ElementalRodAttack.baiprog in SARC content/Actor/Pack/ElementalRodAttack.sbactorpack
>     1: Failed to collect AI program tree roots
>     2: Parameter file missing key: AI program missing Query_13

I get others dealing with missing parameters, as well (I had one yesterday saying that the Recipe section of an sbactorpack was missing an item).

**Comment by NateHevens** [comment] 2023-01-30 18:06
*sigh*

Apologies. I didn't see the BYML strictness thread, which looks like it'll probably solve this issue.

**Comment by NateHevens** [comment] 2023-01-30 18:11
I'm just gonna close this one myself...

**Comment by NateHevens** [comment] 2023-01-30 18:18
Just tried the updated one... still can install Second Wind:

> Failed to process SARC file Actor/Pack/Weapon_Lsword_005.bactorpack
> 
> Caused by:
>     0: Failed to parse resource Actor/Recipe/Weapon_Lsword_005.brecipe in SARC content/Actor/Pack/Weapon_Lsword_005.sbactorpack
>     1: Parameter file missing key: Recipe missing item name

**Comment by NateHevens** [comment] 2023-01-30 18:46
One more...

> Failed to process SARC file Actor/Pack/Enemy_Ghost_Boss.bactorpack
> 
> Caused by:
>     0: Failed to parse resource Actor/AIProgram/Enemy_Ghost_Boss.baiprog in SARC content/Actor/Pack/Enemy_Ghost_Boss.sbactorpack
>     1: Failed to parse AI program demos
>     2: Demo index not an integer
>     3: Found StringRef, expected an integer

**Comment by NiceneNerd** [comment] 2023-01-30 18:51
Clarification: Are you using the BNP or the latest dev build (as a graphic pack)?

**Comment by NateHevens** [comment] 2023-01-30 19:07
Latest dev build. https://github.com/CEObrainz/Second-Wind/releases

**Comment by NiceneNerd** [comment] 2023-01-30 19:14
Hmm, I know some patches were made to Second Wind to get it parsing through UKMM at some point, but I'm not actually sure if there was ever a release made that incorporated them.

**Comment by NateHevens** [comment] 2023-01-30 19:40
Ah okay. Should I reach out there?

**Comment by NateHevens** [comment] 2023-01-30 20:16
I reached out to the SW team. They said that there's some issues, so they're waiting for UKMM and Hyrule Builder to go public.

**Comment by bellisonoroff** [comment] 2023-02-11 18:33
![image](https://user-images.githubusercontent.com/95214548/218275161-405d260b-5bb1-41e4-9bf0-5aa07d807fbd.png)
same issue, any news on this?

**Comment by NiceneNerd** [comment] 2023-02-11 19:02
There's an experimental Second Wind build for UKMM here: https://drive.google.com/file/d/18KH3NWF4EyFF7RSEWP7CoAOLbB5oBgE9/view?usp=drivesdk

So far everything that can be done on the UKMM side has been done, so I'll close this.

**Closed by NiceneNerd** 2023-02-11 19:02 UTC

**Comment by NateHevens** [comment] 2023-02-11 19:24
You are amazing. Thank you so much.

**Comment by NateHevens** [comment] 2023-02-12 20:51
Um... uh... hey @NiceneNerd ... so... I tried to install that and...

> Failed to open mod
> 
> Caused by:
>     Mod missing meta file

**Comment by NiceneNerd** [comment] 2023-02-13 02:21
I just used this today and didn't have that problem. Are you sure you selected the right ZIP when installing?

**Comment by NateHevens** [comment] 2023-02-13 02:33
It's always me, I swear... lol... I'll try again and take screenshots...

**Comment by NateHevens** [comment] 2023-02-13 02:37
All right I uh... I got a screen recording...

https://user-images.githubusercontent.com/36975652/218358073-4c7628f6-0f58-4c40-b56b-57f92f279874.mp4

**Comment by NiceneNerd** [comment] 2023-02-13 02:52
Can you view/open the ZIP elsewhere and make sure it was a good download?

**Comment by NateHevens** [comment] 2023-02-13 02:59
Here's what it looks like inside the .zip file. I just downloaded this, BTW, from the link above... 
![2023-02-12 21 57 11](https://user-images.githubusercontent.com/36975652/218360620-9a2a5fae-d06e-44b6-9889-32c92b14b1b3.jpg)

**Comment by NateHevens** [comment] 2023-02-13 03:01
Inside it is this:

> name: Second Wind
> version: 1.9.13a
> author: CEObrainz
> category: Expansion
> description: Second Wind is a large-scale expansion to Breath of the Wild, aiming to improve upon aspects of the game, add new mechanics as well as adding additional content.
> platform: !Specific Wii U
> url: null
> option_groups: []
> masters: {}

**Comment by NiceneNerd** [comment] 2023-02-13 03:20
Try this: run UKMM from the Command Prompt like so: 
```
set RUST_LOG=trace
ukmm.exe --debug
```

You may also need to check Verbose Logging in the relevant menu,

Then see if the log has anything else to say when the final error shows up.

**Comment by NateHevens** [comment] 2023-02-13 03:53
![2023-02-12 22 52 22](https://user-images.githubusercontent.com/36975652/218366601-b47abc00-4884-477a-b470-b4d8d49a83f8.jpg)

**Comment by NateHevens** [comment] 2023-02-13 03:53
It's gonna be something simple that I'm too ignorant to see, I know it...

**Comment by NiceneNerd** [comment] 2023-02-13 03:54
Is that actually 0.2.3 per the folder name?

**Comment by NateHevens** [comment] 2023-02-13 03:55
It is the .exe that came in the 0.2.3 .zip file...

**Comment by NiceneNerd** [comment] 2023-02-13 03:56
Did you switch to a new version at any point?

**Comment by NateHevens** [comment] 2023-02-13 03:56
I genuinely didn't realize you were on 0.2.5 already. Let me grab that and try again... see what happens.

**Comment by NateHevens** [comment] 2023-02-13 04:00
https://user-images.githubusercontent.com/36975652/218367399-b9789c39-25c9-40ba-bc1f-0632a04c9dae.mp4

**Comment by NateHevens** [comment] 2023-02-13 04:01
I was trying to rung ukmm.exe --debug, BTW, when that happened...

**Comment by NiceneNerd** [comment] 2023-02-13 04:12
The video only shows the browser window

**Comment by NateHevens** [comment] 2023-02-13 04:13
So basically, every time I try to open 0.2.5, that command window pops up, then closes, and nothing happens.

**Comment by NiceneNerd** [comment] 2023-02-13 04:23
There are some critical changes, you'll need to delete your profile from `%LOCALAPPDATA%\ukmm\profiles` most probably

**Comment by NateHevens** [comment] 2023-02-13 04:29
That worked! And suddenly the Second Wind mod installs. Thank you! And sorry for, as usual, being an ignoramous.

**Comment by NiceneNerd** [comment] 2023-02-13 04:35
'Tis my pleasure

**Comment by AceOfCrust** [comment] 2023-04-22 15:36
Sorry if I'm seem like I'm hijacking this topic. 

I was having the same issue with Second Wind, until I got that Google Drive experimental UKMM that was linked here. 

But there was a fix for Eventide, that you installed next to Second Wind. I'm getting the same issue as Second Wind with this Eventide Fix mod, so does the experimental version already have the fix, or is there a experimental UKMM version of the Eventide Fix?

**Comment by NiceneNerd** [comment] 2023-04-25 13:33
What exact issue? It can't be the same exact error because they modify different files.

**Comment by AceOfCrust** [comment] 2023-04-28 11:57
"No dump available for current platform at `crates/uk-manager/src/mods.rs@539:14`"

**Comment by AceOfCrust** [comment] 2023-04-30 14:51
That's funny, considering second wind itself is load (with the experimental build) just fine.

What settings do I need to change, and why do I need to change them for the Eventide Fix since the main second wind loads?

**Comment by AceOfCrust** [comment] 2023-05-01 13:48
So I changed the dump settings and it now shows up on the mod manager as BCML, but whenever I try to apply it I get this error message.

Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Pack/TitleBG.pack at `crates/uk-mod/src/unpack.rs@679:22`
    1: Failed to build file Actor/Pack/Item_Feather.sbactorpack for SARC at `crates/uk-mod/src/unpack.rs@701:18`
    2: Failed to build SARC file Actor/Pack/Item_Feather.sbactorpack at `crates/uk-mod/src/unpack.rs@679:22`
    3: Failed to build file Actor/Chemical/Plant.bchemical for SARC at `crates/uk-mod/src/unpack.rs@701:18`
    4: No base version for file Actor/Chemical/Plant.bchemical at `crates/uk-mod/src/unpack.rs@632:14`

**Comment by DumbledoreCalrissian** [comment] 2023-05-18 11:47
I get this error when I try to install the file provided above -
```
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/FldObj_EnemyBaseRiversideBridge_A_02C.sbactorpack at 'crates/uk-mod/src/unpack.rs@698:22'
    1: Failed to build file Actor/ModelList/FldObj_EnemyBaseRiversideBridge_A_02.bmodellist for SARC at 'crates/uk-mod/src/unpack.rs@720:18'
    2: Failed to parse mod resource Actor/ModelList/FldObj_EnemyBaseRiversideBridge_A_02.bmodellist in mod 'Second Wind' at 'crates/uk-mod/src/unpack.rs@631:73'
    3: error kind: TypeMismatch{ array }, msg: expected map
```
