### ISSUE TITLE
Steam Deck app is extremely scaled up with no way to make it normal

### ISSUE THREAD

**Issue by FiFo101SVK** [NiceneNerd/ukmm#41] opened 2023-02-22 12:19 UTC
![C341BA95-A5D1-48BA-ADBA-F9DF296B5768](https://user-images.githubusercontent.com/65418944/220617733-9951ea89-0a7d-42fc-b2e5-a36440ddbd86.jpeg)

When the steam deck version is used (or the linux one) it is scaled up like this. There is no option to make it smaller, so this renders the app unusuable

**Comment by NiceneNerd** [comment] 2023-02-22 12:24
Duplicate of #18

**Closed by NiceneNerd** 2023-02-22 12:24 UTC
