### ISSUE TITLE
Steam Deck UI

### ISSUE THREAD

**Issue by Leoparodo** [NiceneNerd/ukmm#101] opened 2023-04-21 00:32 UTC
I recently tried to install this on my steam deck and the UI was incredibly large and way to big to be used.

**Comment by Leoparodo** [comment] 2023-04-21 00:35
It also seemed like I couldn't click on any of the buttons beside the settings and mod things near the top(this was done after finagling with the window).

**Comment by NiceneNerd** [comment] 2023-04-21 15:25
Duplicate of a bunch of other issues, it's also already addressed in the docs

**Closed by NiceneNerd** 2023-04-21 15:25 UTC
