### ISSUE TITLE
Launches using incorrect window size on steam deck

### ISSUE THREAD

**Issue by BJack0** [NiceneNerd/ukmm#150] opened 2023-07-04 17:18 UTC
![image](https://github.com/NiceneNerd/ukmm/assets/64874028/fe593687-69c4-4944-b50e-58b02915768a)

Makes navigating the application impossible and can't find a way to fix it.

**Comment by NiceneNerd** [comment] 2023-07-05 14:48
Duplicate of 3843506485 other issues, the solution is in the help docs

**Closed by NiceneNerd** 2023-07-05 14:48 UTC
